# This is a config for E2B sandbox template.
# You can use template ID (p5fbdqrxr8jlkzwmjc2y) or template name (blyzer-nextjs-dev) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("blyzer-nextjs-dev") # Sync sandbox
# sandbox = await AsyncSandbox.create("blyzer-nextjs-dev") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('blyzer-nextjs-dev')

team_id = "b7c5706b-f4f6-4cc6-87be-df1bdbf4d9df"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "blyzer-nextjs-dev"
template_id = "p5fbdqrxr8jlkzwmjc2y"
